data <- as.matrix(read.table(inFile$datapath, header = TRUE, sep="\t", row.names=1, check.names=F))
mean_row <- c()
median_row <- c()
standard_dev <- c()
variance_row <- c()
mad_row <- c()
min_row <- c()
max_row <- c()
sum_row <- c()
for(i in 1:nrow(data))
{
 mean_temp <- mean(as.numeric(data[i,]),na.rm=TRUE)
 median_temp <- median(as.numeric(data[i,]),na.rm=TRUE)
 standard_dev_temp <- sd(as.numeric(data[i,]),na.rm=TRUE)
 variance_temp <- var(as.numeric(data[i,]),na.rm=TRUE)
 mad_temp <- mad(as.numeric(data[i,]),na.rm=TRUE)
 min_temp <- min(as.numeric(data[i,]),na.rm=TRUE)
 max_temp <- max(as.numeric(data[i,]),na.rm=TRUE)
 sum_temp <- sum(as.numeric(data[i,]),na.rm=TRUE)
 mean_row <- c(mean_row,mean_temp)
 median_row <- c(median_row,median_temp)
 standard_dev <- c(standard_dev,standard_dev_temp)
 variance_row <- c(variance_row,variance_temp)
 mad_row <- c(mad_row,mad_temp)
 min_row <- c(min_row,min_temp)
 max_row <- c(max_row,max_temp)
 sum_row <- c(sum_row,sum_temp)
}
output <- cbind(row.names(data),mean_row,median_row,mad_row,standard_dev,variance_row,min_row,max_row,sum_row)
output <- data.frame(output)